### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by sanmulab** [tztztztztz/eqlv2#10]
作者您好！就是我在用你的代码进行训练时报了这个错误，然后我百度查原因是里面有分布式训练代码的问题，然后我想问下为什么eqlv2.py要用分布式配置训练呢，不用分布式怎么解决这个报错

**Comment by sanmulab** [comment]
单GPU不能运行eqlv2吗？

**Comment by tztztztztz** [comment]
@chensen668   你好，因为eqlv2需要统计所有GPU上的正负梯度，所以需要用到分布式中的all_reduce函数。
如果你是单GPU的话，直接去掉对应的allreduce语句即可

**Comment by sanmulab** [comment]
感谢作者哥回复，明天我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tztztztztz/eqlv2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 晚上11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tztztztztz/eqlv2] RuntimeError: Default process group has not been initialized, please make sure to call init_process_group. (#10)





 
@chensen668   你好，因为eqlv2需要统计所有GPU上的正负梯度，所以需要用到分布式中的all_reduce函数。
 如果你是单GPU的话，直接去掉对应的allreduce语句即可
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
