### ISSUE TITLE
Some problems about gradient ratio calculation

### ISSUE THREAD

**Issue by sanmulab** [tztztztztz/eqlv2#17]
self._pos_grad += pos_grad
self._neg_grad += neg_grad
self.pos_neg = self._pos_grad / (self._neg_grad + 1e-10)

Hello, author. I'm sorry to bother you again. I wonder what 1e-10 in the code does? It is not reflected in the formula of the paper.
Is it used to supplement the negative sample gradient?

**Comment by qinwei-hfut** [comment]
I think 1e-10 is used to avoid the error of dividing zero.

**Comment by sanmulab** [comment]
Thank you. I think you're right

> I think 1e-10 is used to avoid the error of dividing zero.

Thank you. I think you're right
