### ISSUE TITLE
About lvis dataset

### ISSUE THREAD

**Issue by U-Help** [tztztztztz/eqlv2#5]
Hello, I'm sorry to bother you but I get into trouble these days. As far as I know, AP is the average of per-category precision. That's same for APr, APc, APf. Therefore, we should have the following equation:
![image](https://user-images.githubusercontent.com/39671748/113169513-410c7b80-9278-11eb-8f43-b8410eb46dc6.png)
However, the statistics are against it. Do you know the reason?

**Comment by tztztztztz** [comment]
Hi, The overall AP is computed by 
<img src="https://render.githubusercontent.com/render/math?math=AP_{overall}=\frac{\sum_{j}^{C} AP_{j}}{C}">

we do not group all categories into three groups (r, c, f) then calculate the average. Instead, the AP is directly aggregated on all categories.

Actually, the computation is more complicated, you can refer to the [implementation details](https://github.com/lvis-dataset/lvis-api/blob/master/lvis/eval.py#L425-L444)
